Parameters:
  KeyName:
    Description: Name of an existing EC2 key pair for SSH access to the EC2 instance.
    Type: AWS::EC2::KeyPair::KeyName
    AllowedPattern : ".+"
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  JenkinsInstanceType:
    Description: EC2 instance type for Jenkins Server
    Type: String
    Default: t2.medium
    AllowedValues:
      - t2.small
      - t2.medium
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - c3.large
      - c3.xlarge
    ConstraintDescription: must be a valid EC2 instance type.

Mappings:
  AWSRegionArch2AMI:
    eu-central-1:
      AMI: ami-0df0e7600ad0913a9
    eu-west-1:
      AMI: ami-099a8245f5daa82bf
    eu-west-2:
      AMI: ami-0389b2a3c4948b1a0
    eu-west-3:
      AMI: ami-0fd9bce3a3384b635
    eu-north-1:
      AMI: ami-074a0e4318181e9d9
    sa-east-1:
      AMI: ami-0ad7b0031d41ed4b9
    us-east-1:
      AMI: ami-0a887e401f7654935
    us-east-2:
      AMI: ami-0e38b48473ea57778
    us-west-1:
      AMI: ami-01c94064639c71719
    us-west-2:
      AMI: ami-0e8c04af2729ff1bb

Resources:
  JenkinsServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - AMI
      InstanceType: !Ref JenkinsInstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref ServerSecurityGroup
        - !Ref SSHSecurityGroup
      Tags:
       - Key: Name
         Value: Jenkins Server
      UserData:
        Fn::Base64: |
           #!/bin/bash
           sudo yum -y update
           sudo yum -y install java-1.8.0
           sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
           sudo rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
           sudo yum -y install jenkins
           sudo systemctl status jenkins
           sudo systemctl enable jenkins.service
           sudo systemctl start jenkins.service
           sleep 15
           sudo cat /var/lib/jenkins/secrets/initialAdminPassword > jenkins-first-access.txt


  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP access via port 8080 + SSH access"
      SecurityGroupIngress:
      - CidrIp: !Ref SSHLocation
        FromPort: '8080'
        IpProtocol: tcp
        ToPort: '8080'
      - CidrIp: !Ref SSHLocation
        FromPort: '22'
        IpProtocol: tcp
        ToPort: '22'
      # if non-default VPC used, specify:
      # SecurityGroupEgress:
      # - IpProtocol: tcp
      #   FromPort: '0'
      #   ToPort: '65535'
      #   CidrIp: 0.0.0.0/0

  # our EC2 security group
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22

  JenkinsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  JenkinsInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref JenkinsRole
  JenkinsPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: JenkinsPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:GetObjectVersion'
              - 's3:PutObject'
              - 's3:DeleteObject'
            Resource: '*'
          - Effect: Allow
            Action:
              - "ec2:AuthorizeSecurityGroupIngress"
              - "ec2:Describe*"
              - "elasticloadbalancing:DeregisterInstancesFromLoadBalancer"
              - "elasticloadbalancing:Describe*"
              - "elasticloadbalancing:RegisterInstancesWithLoadBalancer"
              - "elasticloadbalancing:DeregisterTargets"
              - "elasticloadbalancing:DescribeTargetGroups"
              - "elasticloadbalancing:DescribeTargetHealth"
              - "elasticloadbalancing:RegisterTargets"
            Resource: '*'
      Roles:
        - !Ref JenkinsRole
