apiVersion: v1
kind: Service
metadata:
  labels:
    app: model-ml
  name: model-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: model-ml
  sessionAffinity: None
  type: LoadBalancer
